services:
  atlas:
    build: .
    command: ["incremental", "-d"]
    env_file:
      - .env
      - .env.local
    networks:
      - atlas_default
    volumes:
      - atlas_data:/atlas_data

volumes:
  atlas_data:
    driver: local

networks:
  atlas_default:
    external: true