query AnilistQuery(
  $id: Int!
) {
  Media(id: $id) {
    id
    idMal
    title {
      romaji
      english
      native
    }
    coverImage {
      medium
      large
      extraLarge
    }
    format
    status
    season
    seasonYear
    synonyms
    
    bannerImage
    description
    episodes
    duration
    genres
    averageScore
    
    startDate {
      day
      month
      year
    }
    
    endDate {
      day
      month
      year
    }
    
    nextAiringEpisode {
      episode
      airingAt
      timeUntilAiring
    }
    
    studios {
      edges {
        isMain
        node {
          name
          isAnimationStudio
        }
      }
    }
    
    characters {
      edges {
        node {
          name {
            first
            last
          }
          age
          image {
            large
          }
        }
        role
        voiceActors {
          name {
            first
            last
          }
          image {
            large
          }
        }
      }
    }
    
    relations {
      edges {
        relationType
        node {
          id
          title {
            english
            romaji
            native
          }
          coverImage {
            medium
            large
            extraLarge
          }
          status
          format
        }
      }
    }
    
    recommendations {
      edges {
        node {
          mediaRecommendation {
            id
            title {
              english
              romaji
              native
            }
            coverImage {
              medium
              large
              extraLarge
            }
            status
            format
            averageScore
            seasonYear
          }
        }
      }
    }
    
    trailer {
      thumbnail
      id
      site
    }
    
    externalLinks {
      id
      site
      siteId
      type
      color
      url
    }
  }
}