query ($page: Int, $perPage: Int, $start: FuzzyDateInt, $end: FuzzyDateInt, $sort: [MediaSort], $status_in: [MediaStatus]) {
  Page(page: $page, perPage: $perPage) {
    pageInfo { hasNextPage }
    media(
      startDate_greater: $start, 
      startDate_lesser: $end, 
      sort: $sort, 
      status_in: $status_in, 
      type: ANIME
    ) {
      id
      idMal
      title {
        romaji
        english
        native
      }
      coverImage {
        medium
        large
        extraLarge
      }
      format
      status
      season
      seasonYear
      synonyms
      
      bannerImage
      description
      episodes
      duration
      genres

      tags {
        name
      }

      averageScore
      popularity

      startDate {
        day
        month
        year
      }
      
      endDate {
        day
        month
        year
      }

      updatedAt
    }
  }
}