query ScrapeAnilist($page: Int, $perPage: Int, $start: FuzzyDateInt, $end: FuzzyDateInt) {
  Page(page: $page, perPage: $perPage) {
    pageInfo { 
      total
      hasNextPage
      lastPage
    }
    media(
      type: ANIME
      sort: START_DATE
      startDate_greater: $start
      startDate_lesser: $end
    ) {
      id
      idMal
      title {
        romaji
        english
        native
      }
      coverImage {
        medium
        large
        extraLarge
      }
      format
      status
      season
      seasonYear
      synonyms
      
      bannerImage
      description
      episodes
      duration
      genres
      averageScore
      popularity

      startDate {
        day
        month
        year
      }
      
      endDate {
        day
        month
        year
      }
    }
  }
}